https://github.com/wsargent/docker-cheat-sheet
https://rock-it.pl/how-to-write-excellent-dockerfiles/
########

Write .dockerignore file
Container should do one thing
Understand Docker caching! Use COPY and RUN commands in proper order to utilize that.
Merge multiple RUN commands into one
Remove unneeded files after each step
Use proper base image (alpine versions should be enough)
Set WORKDIR and CMD
Use ENTRYPOINT when you have more than one command and/or need to update files using runtime data
Use exec inside entrypoint script
Prefer COPY over ADD
Specify default environment variables, ports, and volumes inside Dockerfile
#########

