version: '3'

services:
        wordpress:
                image: wordpress
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_HOST: mysql
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: examplePW
                volumes:
                        - wordpress-data:/var/www/html

                links:
                        - 'mysql'

        mysql:
                image: mysql:5.7
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: root
                        MYSQL_PASSWORD: examplePW

                volumes:
                        - mysql-data:/var/lib/mysql

volumes:
        mysql-data:
        wordpress-data


 
